version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    depends_on:
      - db


  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"        # 🔥 로컬에서 3306 → 컨테이너의 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}


