spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root       # 로컬 MySQL 계정
    password: root1234   # 로컬 MySQL 비밀번호 맞게 수정

  jpa:
    hibernate:
      ddl-auto: create   # 실행할 때마다 테이블 drop 후 create (개발 초기 전용)
    properties:
      hibernate:
        format_sql: true
        show_sql: true   # SQL 콘솔 출력
    defer-datasource-initialization: true

  sql:
    init:
      mode: always   # schema.sql, data.sql 실행 (있으면)

  jwt:
    secret: ${JWT_SECRET:my-secret-key}            # .env에서 가져오거나 기본값
    expiration: ${JWT_EXPIRATION:3600000}         # 기본 1시간 (1000ms * 60 * 60)
    issuer: ${JWT_ISSUER:my-app}                  # 기본 발급자